lookupscmcode = {
    ('vermogensmisdrijf') : 'Vermogensmisdrijven',
    ('stelen', 'geweld') : 'Diefstal en inbraak met geweld (WvSr art. 312)',
    ('inbreken', 'geweld') : 'Diefstal en inbraak met geweld (WvSr art. 312)',
    ('diefstal', 'geweld') : 'Diefstal en inbraak met geweld (WvSr art. 312)',
    ('diefstallen', 'geweld') : 'Diefstal en inbraak met geweld (WvSr art. 312)',
    ('overval') : 'Diefstal en inbraak met geweld (WvSr art. 312)',
    ('overvallen') : 'Diefstal en inbraak met geweld (WvSr art. 312)',
    ('stelen') : 'Diefstal en inbraak zonder geweld (WvSr art. 310,311,321-325)',
    ('inbreken') : 'Diefstal en inbraak zonder geweld (WvSr art. 310,311,321-325)',
    ('diefstal') : 'Diefstal en inbraak zonder geweld (WvSr art. 310,311,321-325)',
    ('diefstallen') : 'Diefstal en inbraak zonder geweld (WvSr art. 310,311,321-325)',
    ('bedriegen') : 'Bedrog (WvSr art 326-338)',
    ('oplichten') : 'Oplichting (WvSr art. 326)',
    ('flessentrekkerij') : 'Flessentrekkerij (WvSr art. 326a)',
    ('valsheidsmisdrijf') : 'Valsheidsmisdrijven (WvSr art. 208-214, 216-223, 225-234)',
    ('muntmisdrijf') : 'Muntmisdrijf (WvSr art. 208-214)',
    ('valsheid in geschriften') : 'Valsheid in geschriften (WvSr art. 225-234)',
    ('helen') : 'Heling (WvSr art. 416-417bis)',
    ('afpersen') : 'Afpersing en afdreiging (WvSr art. 317-318)',
    ('bankbreuk') : 'Bankbreuk (WvSr art. 340-343)',
    ('witwassen') : 'Witwassen (WvSr art. 420bis-420quater)',
    ('vernielen') : 'Vernieling en beschadiging (WvSr art. 350-352)',
    ('beschadigen') : 'Vernieling en beschadiging (WvSr art. 350-352)',
    ('vernielen', 'auto') : 'Vernieling aan auto',
    ('beschadigen', 'auto') : 'Vernieling aan auto',
    ('vernielen', 'gebouw') : 'Vernieling aan openbaar gebouw',
    ('beschadigen', 'gebouw') : 'Vernieling aan openbaar gebouw',
    ('vernielen', 'trein') : 'Vernieling aan middel openbaar vervoer',
    ('beschadigen', 'trein') : 'Vernieling aan middel openbaar vervoer',
    ('vernielen', 'bus') : 'Vernieling aan middel openbaar vervoer',
    ('beschadigen', 'bus') : 'Vernieling aan middel openbaar vervoer',
    ('vernielen', 'tram') : 'Vernieling aan middel openbaar vervoer',
    ('beschadigen', 'tram') : 'Vernieling aan middel openbaar vervoer',
    ('vernielen', 'metro') : 'Vernieling aan middel openbaar vervoer',
    ('beschadigen', 'metro') : 'Vernieling aan middel openbaar vervoer',
    ('dierenmishandeling') : 'Dierenmishandeling',
    ('geweld') : 'Openlijke geweldpleging tegen persoon (WvSr art. 141)',
    ('geweldpleging') : 'Openlijke geweldpleging tegen persoon (WvSr art. 141)',
    ('huisvredebreuk') : 'Huisvredebreuk (WvSr art. 138)',
    ('lokaalvredebreuk') : 'Lokaalvredebreuk (WvSr art. 139)',
    ('computervredebreuk') : 'Computervredebreuk (WvSr art. 138ab, 138b)',
    ('computer', 'inbreken') : 'Computervredebreuk (WvSr art. 138ab, 138b)',
    ('cybercrime') : 'Computervredebreuk (WvSr art. 138ab, 138b)',
    ('discriminatie') : 'Discriminatie (WvSr art. 137c-137g)',
    ('brandstichten') : 'Brandstichting/ontploffing (WvSr art. 157-158)',
    ('brandstichting') : 'Brandstichting/ontploffing (WvSr art. 157-158)',
    ('brandstichtingen') : 'Brandstichting/ontploffing (WvSr art. 157-158)',
    ('brand', 'stichten') : 'Brandstichting/ontploffing (WvSr art. 157-158)',
    ('brand', 'gesticht') : 'Brandstichting/ontploffing (WvSr art. 157-158)',
    ('bevel') : 'Niet opvolgen van ambtelijk bevel (WvSr art. 184)',
    ('wederspannigheid') : 'Wederspannigheid (WvSr art. 180-182)',
    ('verzetten') : 'Wederspannigheid (WvSr art. 180-182)',
    ('valse aangifte') : 'Valse aangifte (WvSr art. 188)',
    ('verblijven', 'vreemdeling') : 'Verblijf van ongewenste vreemdeling (WvSr art. 197)',
    ('mishandelen') : 'Mishandeling (WvSr art. 300-306)',
    ('bedreigen') : 'Bedreiging (WvSr art. 284a-285a)',
    ('stalken') : 'Stalking (WvSr art. 285b)',
    ('aanranden') : 'Aanranding  (WvSr art. 246)',
    ('verkrachten') : 'Verkrachting (WvSr art. 242)',
    ('schenden', 'eerbaarheid') : 'Schennis der eerbaarheid (WvSr art. 239)',
    ('ontucht') : 'Ontucht met minderjarige (WvSr art. 248a-248e)',
    ('porno') : 'Pornografie (WvSr art. 240-240b)',
    ('pornografie') : 'Pornografie (WvSr art. 240-240b)',
    ('ontucht', 'gezag') : 'Ontucht met misbruik van gezag (WvSr art. 249)',
    ('gijzelen') : 'Vrijheidsbeneming/gijzeling (WvSr art. 282-282a)',
    ('mensenhandel') : 'Mensenhandel (WvSr art. 273f)',
    ('verkeersmisdrijf') : 'Verkeersmisdrijven',
    ('verlaten', 'ongeval') : 'Verlaten plaats ongeval (WVW art. 7)',
    ('wegrijden', 'ongeval') : 'Verlaten plaats ongeval (WVW art. 7)',
    ('dronken', 'rijden') : 'Rijden onder invloed (WVW art. 8)',
    ('rijden onder invloed') : 'Rijden onder invloed (WVW art. 8)',
    ('rijden zonder rijbewijs') : 'Rijden tijdens ontzegging/onbevoegd besturen (WVW art. 9)',
    ('rijden', 'verbod') : 'Rijden tijdens rijverbod (WVW art. 162)',
    ('vals kenteken') : 'Voeren vals kenteken (WVW art. 41)',
    ('joyriden') : 'Joyriding (WVW art. 11)',
    ('blaastest') : 'Weigeren blaastest/bloedonderzoek e0d0 (WVW art. 163)',
    ('drugsmisdrijf') : 'Drugsmisdrijven',
    ('harddrugs') : 'Harddrugs (Opiumwet art. 2)',
    ('heroine') : 'Harddrugs (Opiumwet art. 2)',
    ('cocaine') : 'Harddrugs (Opiumwet art. 2)',
    ('xtc') : 'Harddrugs (Opiumwet art. 2)',
    ('speed') : 'Harddrugs (Opiumwet art. 2)',
    ('softdrugs') : 'Softdrugs (Opiumwet art. 3)',
    ('wiet') : 'Softdrugs (Opiumwet art. 3)',
    ('vuurwapen') : '(Vuur)wapenmisdrijven',
    ('wapen') : '(Vuur)wapenmisdrijven',
    ('militair misdrijf') : 'Militaire misdrijven (WvMSr art. 96-166)'
}
if __name__ == '__main__':
    for k in lookupscmcode.keys():
        if isinstance(k, tuple):
            for l in k:
                print(l)
        else:
            print(k)